# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'DemoPublishLibs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoPublishLibs

  pod 'DemoPublishLibs', :git => 'git@github.com:joinself/demo-publish-libs.git'
end
